### ISSUE TITLE
Problem with llvmlite while running gimble parse

### ISSUE THREAD

**Issue by pierrebarry** [LohseLab/gIMble#101]
Hello,

I am trying to running gimble but I encountered a problem on the second step gimble parse:

[+] Running 'gimble parse' ...
[X] ImportError: Numba requires at least version 0.39.0 of llvmlite.
Installed version is 0.36.0.
Please update llvmlite.

I have installed gimble with the following commands:

```
# 1. clone repository
>>> git clone https://github.com/DRL/gimble.git
# 2. Install miniconda from https://conda.io/miniconda.html
# ...
# 3. Create the following conda environment 
>>> conda create -n gimble python=3.7.12 agemo bedtools bcftools samtools vcflib mosdepth=0.3.2 pysam numpy docopt tqdm pandas tabulate zarr scikit-allel parallel matplotlib msprime demes dask numcodecs python-newick nlopt -c conda-forge -c bioconda
# 4. Load the environment (needs to be activated when using gimble)
>>> conda activate gimble
# 5. Start gimble'ing ...
>>> (gimble) gIMble/gimble --help
```

and gimble preprocess worked fine. 

With `conda list` I can see that agemo and llvmlite are installed:

```
# Name                    Version                   Build  Channel
agemo                     0.0.2              pyhd8ed1ab_0    conda-forge
llvmlite                  0.39.0           py37he1b5a44_0    numba
```

Strangely, the error message does not match with this description as gimble found only the 0.36.0 version of llwmlite and here it is shown that it is the 0.39.0 version of llvmlite that is installed. Can it be because it was installed with numba and not conda-forge ? It is the only package in the conda list that has the description numba in the Channel column.

Thank you very much for your help,

Pierre

**Comment by GertjanBisschop** [comment]
Hi Pierre, 
Thanks for bringing this to our attention. The numba channel is definitely right. The is definitely not the cause of the issue.
@DRL depends on python 3.8. I am wondering whether the python constraint is causing issues here. Python dependencies might have been given a bump recently since python 3.7 is now EOL.

**Comment by DRL** [comment]
Closed, as it should be solved with current installation method
