### ISSUE TITLE
gimble makegrid usage

### ISSUE THREAD

**Issue by juanitagutierrez** [LohseLab/gIMble#114]
Hi all, 

I have been trying some gIMble modules for my analyses, and I just reached the `makegrid` step (I also installed the latest version of the program upon its publication in PLoS Genetics). 
I have two questions that I would be grateful to get your help with :)
1- After running the `optimization` model, I tried obtaining the grid with the parameters I obtained for the best fitting model as:
`gimble makegrid -z test_parsed.z -m IM_AB -b 64 -r A_B -u 2.9e-9 -k 2,2,2,2 -A=100_000,500_000,12,lin -B=100_000,500_000,12,lin -C=300_000,700_000,12,lin -T=200_000 -M 0,2.16E-07,16,lin -p 48 -e 19 -l IM_AB_01
`, and I get the following message: `zstore already exists. Specify using -z or provide new prefix.`
Is this the expected behavior, when I am already specifying the name of the zstore? From what I understood, it should be possible to store the grid results in the same zstore to further conduct the `gridsearch`, isn't this the case? The command only works when I specify `--outprefix` to create a new zstore. 
2- When I get to run `makegrid` (by specifying `--outprefix`), I also receive the following warning: `XX anomalies detected. Please consider changing the parameter space as this grid might behave strangely.` In this case, is it advisable to repeat the optimization step after having run `makegrid` to better inform parameter boundaries for each parameter? 

Thanks in advance for your help!

**Comment by GertjanBisschop** [comment]
Thanks @juanitagutierrez for reaching out. 
1. This seems to be a bug. @DRL, the default outprefix for makegrid seems to be gimble, should this not be None such that `_get_prefix()` returns None if no outprefix is specified?
2. Does the new zstore contain blocked data? If not then we would probably have to raise a more informative error. I suspect that the anomalies reported have to do with numerical stability issues in agemo for some parameter combinations. Here as well, I think we would have to raise a more informative error such that people would now what and why they might have to change the grid they are running.

**Comment by DRL** [comment]
Hi @juanitagutierrez,

> 1- After running the optimization model, I tried obtaining the grid with the parameters I obtained for the best fitting model as:
gimble makegrid -z test_parsed.z -m IM_AB -b 64 -r A_B -u 2.9e-9 -k 2,2,2,2 -A=100_000,500_000,12,lin -B=100_000,500_000,12,lin -C=300_000,700_000,12,lin -T=200_000 -M 0,2.16E-07,16,lin -p 48 -e 19 -l IM_AB_01 , and I get the following message: zstore already exists. Specify using -z or provide new prefix.
Is this the expected behavior, when I am already specifying the name of the zstore? From what I understood, it should be possible to store the grid results in the same zstore to further conduct the gridsearch, isn't this the case? The command only works when I specify --outprefix to create a new zstore.

I can't replicate this behaviour. Using `gimble v1.0.3` i can run an equivalent command to yours and it creates a grid in an existing zstore. Are you sure you are using this command as is `gimble makegrid -z test_parsed.z -m IM_AB -b 64 -r A_B -u 2.9e-9 -k 2,2,2,2 -A=100_000,500_000,12,lin -B=100_000,500_000,12,lin -C=300_000,700_000,12,lin -T=200_000 -M 0,2.16E-07,16,lin -p 48 -e 19 -l IM_AB_01`?

Can you maybe post the entire command and output from gimble to see what's going on?

> 2- When I get to run makegrid (by specifying --outprefix), I also receive the following warning: XX anomalies detected. Please consider changing the parameter space as this grid might behave strangely. In this case, is it advisable to repeat the optimization step after having run makegrid to better inform parameter boundaries for each parameter?

Some parameter combinations yield strange results in the sense that they violate basic assumptions as to how the probabilities of bSFS configurations should look like. We call those "anomalies". No need to repeat the optimization, just run `makegrid` with slightly different values, Best solution is to add or subtract an integer from `T` or slightly shift the grid by one integer in some direction (for the `Ne` values, not for `M`). This will get rid of the anomalies.

cheers,

dom

**Comment by juanitagutierrez** [comment]
Hi @DRL and @GertjanBisschop,

Thanks for your interest in helping with this!
I tried running the command again. I can confirm I am using the line of code that I posted earlier in this thread. 
Input line:
`gimble makegrid -z test_parsed.z -m IM_AB -b 64 -r A_B -u 2.9e-9 -k 2,2,2,2 -A=100_000,500_000,12,lin -B=100_000,500_000,12,lin -C=300_000,700_000,12,lin -T=200_000 -M 0,2.16E-07,16,lin -p 48 -e 19 -l IM_AB_01`
Output:
`[+] Running 'gimble makegrid' ...
[X] zstore already exists. Specify using -z or provide new prefix.

In case this is of any use, I am sharing below the output of `gimble info -z test_parsed.z`

`[+] Running 'gimble info' ...
[+] Getting report. This might take a while ...
[+] 	 Getting storage info ...
[+] 	 Getting parse info...
[+] 	 Getting blocks info...
[+] 	 Getting windows info...
[+] 	 Getting tally info...
[+] 	 Getting simulate info...
[+] Writing info file ven_che_n11_allopatric_parse_121023.info.txt ...
[+] [ =========================================== Storage =========================================== ]
[+] ven_che_n11_allopatric_parse_121023.z ........................................... 28.0 MB | 100.00%
[+] ├── blocks ....................................................................... 1.8 MB |   6.46%
[+] ├── seqs ........................................................................ 25.9 MB |  92.33%
[+] ├── tally ....................................................................... 91.7 KB |   0.32%
[+] └── windows .................................................................... 253.0 KB |   0.88%
[+] [ ========================================= Parsed data ========================================= ]
[+] seqs                                                                                               
[+] ├── genome ....................................... 9,082,537 b in 2 sequence(s) (n50 = 5,168,646 b)
[+] ├── populations ....................................................... 11 samples in 2 populations
[+] │  ├── A = sp_1                                                                                    5
[+] │  └── B = sp_2                                                                                   6
[+] ├── sample sets ................................................................................ 55
[+] │  ├── INTER-population sample-sets (X)                                                          30
[+] │  ├── INTRA-population sample-sets (A)                                                          10
[+] │  └── INTRA-population sample-sets (B)                                                          15
[+] ├── variants ............................................................. 765,517 (84.28 per 1 kb)
[+] │  │                                                                 HOMREF  HOMALT     HET    MISS
[+] │  ├── sp_1_01				                                         73.37%  14.15%   5.09%   7.39%
[+] │  ├── sp_1_02                                      				 73.46%  14.31%   4.93%   7.31%
[+] │  ├── sp_1_03                                        		         73.61%  14.26%   5.02%   7.12%
[+] │  ├── sp_1_04                                                       73.23%  13.77%   6.14%   6.86%
[+] │  ├── sp_1_05                                                       73.55%  14.12%   5.11%   7.22%
[+] │  ├── sp_2_01                                                		 28.82%   3.34%   4.34%  63.50%
[+] │  ├── sp_2_02                                                 		 38.06%   4.48%   5.95%  51.52%
[+] │  ├── sp_2_03                                            			 16.58%   1.74%   2.44%  79.25%
[+] │  ├── sp_2_04                                            			 11.96%   1.21%   1.77%  85.05%
[+] │  ├── sp_2_05                                          			 20.79%   2.26%   3.17%  73.78%
[+] │  └── sp_2_06                                           			 20.84%   2.28%   3.17%  73.71%
[+] └── intervals ............................. 868,354 intervals across 3,039,562 b (33.47% of genome)
[+] [ ============================================ Blocks =========================================== ]
[+] blocks/                                                                                            
[+] ├── '-l 64 -m 128 -u 3 -i 3' ....................................  328,245 blocks (0.31% discarded)
[+] │                                                                     X             A             B
[+] ├── BED interval sites in blocks (estimated %)                    6.89%        46.31%         1.43%
[+] ├── Total blocks                                                 98,131       219,939        10,175
[+] ├── Invariant blocks                                             83.83%        92.60%        88.57%
[+] ├── Four-gamete-violation blocks                                  0.07%         0.02%         0.04%
[+] ├── Heterozygosity (population A)                               0.00120       0.00169             -
[+] ├── Heterozygosity (population B)                               0.00248             -       0.00194
[+] ├── D_xy                                                        0.00426             -             -
[+] ├── F_st                                                        0.39538             -             -
[+] ├── Pi                                                                -       0.00159       0.00190
[+] └── Watterson theta                                                   -       0.00156       0.00190
[+] [ =========================================== Windows =========================================== ]
[+] windows/                                                                                           
[+] └── '-w 500 -s 100' .................................... 973 windows of inter-population (X) blocks
[+] [ =========================================== Tallies =========================================== ]
[+] tally/                                                                                             
[+] [ ========================================= Simulations ========================================= ]
[+] simulate/                                                                                          
[*] Total runtime was 00h:00m:16.093s`

Cheers :)

**Comment by DRL** [comment]
Do you have `gimbleprep` installed in the same conda environment? 

If so, could you check whether the problem persists in a conda environment that only has `gimble`?

Also can you check whether the issue also arises if you use only one process (`-p 1`)?

Sorry for the troubles.

dom

**Comment by juanitagutierrez** [comment]
Hi again, and thanks for your reply and willingness to help. 
Well, actually, one of the issues that I have had is the installation of `gimbleprep` itself, although the latest version of `gimble`(without the preprocessing module) can be installed. Because of this, I was still using the `preporcess` module from the earlier version of the pipeline. I guess this could be the first thing to fix. Could it be that I need to install `gimbleprep` and it's dependencies explicitly? Best wishes,

**Comment by GertjanBisschop** [comment]
Did you install `gimbleprep` by running `conda install -c bioconda gimbleprep`?

**Comment by juanitagutierrez** [comment]
> Did you install `gimbleprep` by running `conda install -c bioconda gimbleprep`?

Hi Gertjan, yes, I followed the installation instructions as specified in here, but it still doesn't work. I even contacted the support team of the cluster I am using, and they couldn't install it either and recommended getting in touch with the authors of the program asking if you guys would have any hints on what might be happening.

**Comment by GertjanBisschop** [comment]
Can you paste in the error message you are getting following your installation as well as everything that is installed in your conda environment so we can try and replicate the issue.

**Comment by juanitagutierrez** [comment]
Hi again, I had to start working on a different cluster where I managed install both `gimbleprep` and `gimble`. I will create a another issue with a different problem that I have encountered already at the `gimbleprep` stage. Thanks!
