### ISSUE TITLE
gimbleprep can't create filtered vcf

### ISSUE THREAD

**Issue by juanitagutierrez** [LohseLab/gIMble#127]
Hi,

I am using `gimbleprep`. The job proceeds as expected until it has to create the filtered vcf (note: it does create `multi_callable.bed`).

These are the commands I am using:
`source activate gimbleprep_again`
`conda activate gimbleprep_again`

Then:
`gimbleprep --fasta_file assembly_final_corrected.fa --vcf_file prefiltered.biallelic_snp.inv.masked_reps.ab_0.2_0.8.subset_6000000.vcf.gz --bam_dir bam_files --snpgap 2 --min_qual 8 --min_depth 10 --max_depth 2 --threads 6 --keep_tmp --outprefix test_gimbleprep`

The error:
`bcftools norm --threads 6 -Ov -f path/to/assembly_final_corrected.fa path/to/prefiltered.biallelic_snp.inv.masked_reps.ab_0.2_0.8.subset_6000000.vcf.gz |                 vcfallelicprimitives --keep-info --keep-geno -t decomposed |                 bcftools plugin fill-AN-AC --threads 6 -Oz |                 bcftools filter --threads 6 -Oz -s Qual -m+ -e 'QUAL<10' |                 bcftools filter --threads 6 -Oz -m+ -s+ --SnpGap 2 |                 bcftools filter --threads 6 -Oz -e 'TYPE!="snp"' -s NonSnp -m+ > tmp_gimble_ape6un8i/vcf.filtered.vcf.gz`

`(STDERR): 'Failed to read from standard input: unknown file type\nFailed to read from standard input: unknown file type\nFailed to read from standard input: unknown file type\nFailed to read from standard input: unknown file type'`

Also, I must clarify that I used `bcftools` instead of `freebayes` to create the vcf. Is this expected to cause issues of this kind? Since I knew that the main problem would be that allele imbalance filters couldn't be applied unless `freebayes` was used, I also pre-filtered for allele imbalance using `bcftools`.
Thanks in advance for any help you can provide!

**Comment by GertjanBisschop** [comment]
I have moved this issue to the gimbleprep repo.
