### ISSUE TITLE
Missing dependencies when Running 'gimble parse' 

### ISSUE THREAD

**Issue by hrluo93** [LohseLab/gIMble#99]
I have followed the Installation guideline do  
1. git clone https://github.com/DRL/gimble.git
2. mamba create -n gimble python=3.7.12 agemo bedtools bcftools samtools vcflib mosdepth=0.3.2 pysam numpy docopt tqdm pandas tabulate zarr scikit-allel parallel matplotlib msprime demes dask numcodecs python-newick nlopt -c conda-forge -c bioconda
3. conda activate gimble 
4. gimble preprocess
when I running gimble parse, two HPC and one local workstation both report Missing dependencies. Did i missed some steps? this is my "conda list" result.

Best wishes!
Ran 
[conda-list.txt](https://github.com/DRL/gIMble/files/11951454/conda-list.txt)

**Comment by hrluo93** [comment]
Dear dom, 

    Many thanks for your reply~
    I am sure that I activated env when I am running gimble.

Best wishes!
Ran
![2023-07-05 20-23-43屏幕截图](https://github.com/DRL/gIMble/assets/57522086/977b1ffd-0590-41b6-97c9-864ea86b3bc7)

**Comment by DRL** [comment]
Hmm... very odd. Just made a new environment on my machine and could not replicate the error.

Can you check whether you have the latest version of `gimble`? (do a git pull in the `gimble` folder)

**Comment by hrluo93** [comment]
Dear dom,
  
     I have checked the version I used was 1.0.3 and run git pull.
     I also create a new env by
     1. conda create -n gimble1 python=3.7.12 bedtools bcftools samtools vcflib mosdepth=0.3.2 pysam numpy docopt tqdm pandas tabulate zarr scikit-allel parallel matplotlib msprime demes dask numcodecs python-newick nlopt -c conda-forge -c bioconda
     2. conda activate gimble1
     3. pip install agemo
     
    However, still report Missing dependencies.
    I attached two file csv and genome file (My chr IDs could a bit long). 

Best wishes！
![2023-07-05 21-02-46屏幕截图](https://github.com/DRL/gIMble/assets/57522086/a275723a-5783-4b63-8c41-079c4bf40196)
![2023-07-05 21-01-41屏幕截图](https://github.com/DRL/gIMble/assets/57522086/029e0ce9-4b70-4570-80d7-c46ae629bd4a)

**Comment by DRL** [comment]
Input files look fine and that should not matter since the depency error gets displayed when any of the imports fails... 

But you do **not** need to run `pip install agemo` ... this was changed a few weeks ago. 

Did you also do that the first time? That could be the problem ...

**Comment by hrluo93** [comment]
> Input files look fine and that should not matter since the depency error gets displayed when any of the imports fails...
> 
> But you do **not** need to run `pip install agemo` ... this was changed a few weeks ago.
> 
> Did you also do that the first time? That could be the problem ...

The first time I used Conda to install agemo, I am trying to install it in the new local server as well as in the Vmware now. Maybe need a few days. Thanks for your reply!

**Comment by hrluo93** [comment]
Dear DRL,

I guess the possible reason is cached packages' dependencies missing because of the undefined versions of them, when I am trying to update env, some packages' dependencies showed will remove by conda.

could you plz share the yaml file of the env? conda env export -n gimble > gimble-env.yaml
So that I can use conda env create -f  gimble-env.yaml to create the correct environment. 

Many thanks!
Best wishes!

**Comment by yangfangyuan0102** [comment]
Hi, @hrluo93 , have you slove it? I met this issue too.

**Comment by hrluo93** [comment]
> Hi, @hrluo93 , have you slove it? I met this issue too.

Hi, [yangfangyuan0102](https://github.com/yangfangyuan0102)! 
This issue is not solved.
I try to manually run the script line by line.
I found that the possible issue is caused by "TypedDict" from 'typing'
So I think the best way is for the author @DRL to send the conda yaml
![image](https://github.com/DRL/gIMble/assets/57522086/fda0de90-9192-4131-b2d7-504252358724)

Best wishes！
Ran

**Comment by LeebanY** [comment]
Hi @hrluo93, @yangfangyuan0102, @DRL ,

Ran into this problem too and it seems this can be solved by changing, 'typing' to 'typing_extensions' in the file: 
/mnt/shared/scratch/ly/apps/conda/envs/gimble/lib/python3.7/site-packages/zarr/context.py. 

Unsure if this has downstream consequences on other gimble modules. @DRL is infinitely more capable at answering that than I am, but I hope this helps resolve the immediate issue. Will post again if this has not fixed the issue.

Cheers,
Leeban

**Comment by DRL** [comment]
Yeah, this is a workaround but we are now in the process of packaging `gimble` as a proper conda recipe so that this should not happen again in the future. 

Most likely this occurs only in rare combinations of installed libraries on the node which then causes conda to install some libraries (in this case a version of zarr) that try to import uninstalled libraries. But debugging is difficult as i have not been able to replicate this reliably on our machines ...

**Comment by DRL** [comment]
Closed, as it should be solved with current installation method
